title: 100 Days To Offload # Add the title for your site here.
description: Can you publish 100 posts on your blog in a year? # Add a description for your site here.
lang: en
locale: en_GB # Change this based on your locale - https://www.w3schools.com/tags/ref_language_codes.asp
url: "https://100daystooffload.com" # Add you site's domain here. E.g. "https://example.com"
logo: /assets/images/favicon.webp # Change this to be your favicon
email: 100days@qrk.one
# You don't need to change any of this stuff
baseurl: ""
permalink: :title

# Syntax Highlighting
highlighter: rouge

# If you want to add more plugins, do so here
plugins:
  - jekyll-sitemap
